### ISSUE TITLE
 Could not find method fern() for arguments...

### ISSUE THREAD

**Issue by baneeishaque** [nishtahir/fern#1]
Trying to test fern. Here is my build.gradle file...
`    buildscript {

    repositories {
        maven { url "https://jitpack.io" }
		jcenter()
    }

    dependencies {
        classpath "com.github.nishtahir:fern:-SNAPSHOT"
    }
}

apply plugin: "com.nishtahir.fern"

fern {
     classesDir = "" // Directory to scan for class files
     outputDir = ""  // output directory

     removeBridge = true
     removeSynthetic = false
     decompileInner = true
     decompileClass14 = true
     decompileAssertions = true
     hideEmptySuper = true
     hideDefaultConstructor = true
     decompileGenericSignatures = false
     noExceptionsReturn = true
     decompileEnum = true
     removeGetClassNew = true
     literalsAsIs = false
     booleanTrueOne = true
     asciiStringCharacters = false
     syntheticNotSet = true
     undefinedParamTypeObject = true
     useDebugNames = true
     removeEmptyRanges = true
     finallyDeinline = true
     ideaNotNullAnnotation = true
     lambdaToAnonymousClass = false
     bytecodeSourceMapping = false
     logLevel = "info"
     maxProcessingMethod = false
     renameEntities = false
     userRenamerClass = false
     newLineSeparator = false
     indentString = "    "
     banner = ""
     dumpOriginalLines = false
     unitTestMode = false
}`

but i got this error on running `gradle build` ...

`$ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\DK-HP-PA-2000AR\Laboratory\CMD_Gradle\Fern-demo\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'Fern-demo'.
> Could not find method fern() for arguments [build_8z6fa2ala5jwd1pyzilw7046o$_run_closure1@1d3f867d] on root project 'Fern-demo' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2s
`

**Comment by nishtahir** [comment]
Thanks for reporting the issue. Here's a build script that's worked for me

```
buildscript {
    ext.kotlin_version = "1.1.2"

    repositories {
        maven { url "https://jitpack.io" }
        mavenCentral()
    }
    dependencies {
        classpath "com.github.nishtahir:fern:7bd46db119"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "kotlin"
apply plugin: "com.nishtahir.fern"

fern {
    logLevel = "warn"
}

repositories {
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
}

```

Note that fern requires either the `kotlin` or `kotlin-android` plugins to be applied for the configurations to be applied to the build script.

**Comment by baneeishaque** [comment]
How to use this plugin? can you please provide an example repository?
I used the following build.gradle, the build is success - but nothing happened...

` buildscript {
	ext.kotlin_version = "1.1.3-2"
    repositories {
        maven { url "https://jitpack.io" }
		jcenter()
    }

    dependencies {
        classpath "com.github.nishtahir:fern:-SNAPSHOT"
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "kotlin"
apply plugin: "com.nishtahir.fern"

fern {
     classesDir = "src" // Directory to scan for class files
     outputDir = "src"  // output directory

     removeBridge = true
     removeSynthetic = false
     decompileInner = true
     decompileClass14 = true
     decompileAssertions = true
     hideEmptySuper = true
     hideDefaultConstructor = true
     decompileGenericSignatures = false
     noExceptionsReturn = true
     decompileEnum = true
     removeGetClassNew = true
     literalsAsIs = false
     booleanTrueOne = true
     asciiStringCharacters = false
     syntheticNotSet = true
     undefinedParamTypeObject = true
     //useDebugNames = true
     removeEmptyRanges = true
     finallyDeinline = true
     ideaNotNullAnnotation = true
     lambdaToAnonymousClass = false
     bytecodeSourceMapping = false
     logLevel = "info"
     maxProcessingMethod = false
     renameEntities = false
     userRenamerClass = false
     newLineSeparator = false
     indentString = "    "
     banner = ""
     dumpOriginalLines = false
     unitTestMode = false
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
}`

Here is my project structue, the src file contains a simple class file which i want to decompile ( a hello world program in java for testing purpose)...

![image](https://user-images.githubusercontent.com/6133009/27996907-6b6376da-650a-11e7-9682-1088f322e550.png)

Note : i am using _ext.kotlin_version = "1.1.3-2"_ - the latest version
_jcenter()_ - which preferred over mavenCentral()
_classpath "com.github.nishtahir:fern:-SNAPSHOT"_ - got from jitpack.io
_fern {
     classesDir = "src" // Directory to scan for class files
     outputDir = "src"  // output directory

     removeBridge = true
     removeSynthetic = false
     decompileInner = true
     decompileClass14 = true
     decompileAssertions = true
     hideEmptySuper = true
     hideDefaultConstructor = true
     decompileGenericSignatures = false
     noExceptionsReturn = true
     decompileEnum = true
     removeGetClassNew = true
     literalsAsIs = false
     booleanTrueOne = true
     asciiStringCharacters = false
     syntheticNotSet = true
     undefinedParamTypeObject = true
     //useDebugNames = true
     removeEmptyRanges = true
     finallyDeinline = true
     ideaNotNullAnnotation = true
     lambdaToAnonymousClass = false
     bytecodeSourceMapping = false
     logLevel = "info"
     maxProcessingMethod = false
     renameEntities = false
     userRenamerClass = false
     newLineSeparator = false
     indentString = "    "
     banner = ""
     dumpOriginalLines = false
     unitTestMode = false
}_  - got from your documentation, can you please explain what is these options, and useDebugNames throws errors ( thats why i commented it)?

_dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
}_  - is this part necessory (i got build success without that) ?

**Comment by nishtahir** [comment]
I've removed the hard requirement on kotlin on the project. So it should work with what you are trying to do. 

Here's a sample for you to try.
```
buildscript {

    repositories {
        maven { url "https://jitpack.io" }
        mavenCentral()
    }
    dependencies {
        classpath "com.github.nishtahir:fern:35703ad2a4"
    }
}

apply plugin: "com.nishtahir.fern"

fern {
    //set your sources root
    classesDir="src"
}
```

Do not set the `outputDir` to the same folder as the `classesDir`. If you do, it will delete everything in there.

Documentation on the properties can be found [here](https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine)

**Comment by baneeishaque** [comment]
Tested successfully, here is my build.gradle file...

`  buildscript {
	ext.kotlin_version = "1.1.3-2"
    repositories {
        maven { url "https://jitpack.io" }
		jcenter()
    }

    dependencies {
        classpath "com.github.nishtahir:fern:-SNAPSHOT"
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "kotlin"
apply plugin: "com.nishtahir.fern"

fern {
     classesDir = "src" // Directory to scan for class files
     outputDir = "out"  // output directory

     removeBridge = true
     removeSynthetic = false
     decompileInner = true
     decompileClass14 = true
     decompileAssertions = true
     hideEmptySuper = true
     hideDefaultConstructor = true
     decompileGenericSignatures = false
     noExceptionsReturn = true
     decompileEnum = true
     removeGetClassNew = true
     literalsAsIs = false
     booleanTrueOne = true
     asciiStringCharacters = false
     syntheticNotSet = true
     undefinedParamTypeObject = true
     //useDebugNames = true
     removeEmptyRanges = true
     finallyDeinline = true
     ideaNotNullAnnotation = true
     lambdaToAnonymousClass = false
     bytecodeSourceMapping = false
     logLevel = "info"
     maxProcessingMethod = false
     renameEntities = false
     userRenamerClass = false
     newLineSeparator = false
     indentString = "    "
     banner = ""
     dumpOriginalLines = false
     unitTestMode = false
} `

Here is my directory structure...
![image](https://user-images.githubusercontent.com/6133009/28003241-d6788420-6559-11e7-9430-5cf79dc42b7c.png)

src folder contains class files which are to be decompile and out folder contains decompiled files. 
Please close the issue...
